# Generated by Django 3.2.4 on 2021-06-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20210628_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
