# Generated by Django 3.2.4 on 2021-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_auto_20210630_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
